[package]
name = "secp256k1_ecdsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigint = "4.4"
rand = "0.8"
blake3 = "1.3"
