[package]
name = "ed25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigint = "4.4"
rand = "0.8"
sha2 = "0.10.2"
serde = { version = "1.0.1", features = ["derive"] }
serde_json = "1.0"
